#Load libraries
library(sf)
library(dplyr)
library(leaflet)
library(leaflet.extras)
library(arcgislayers)
library(tidyr)
library(ggplot2)
library(scico)
library(wesanderson)
library(htmltools)
library(htmlwidgets)
library(DT)
library(shinyjs)
library(stringr)
library(openxlsx)
library(purrr)
library(readr)
library(robis)
library(bslib)
library(shiny)
library(phyloseq)
library(taxplore)  #Here is the link for taxplore tutorial in Shiny: https://markschl.github.io/taxplore/articles/tutorial.html#shiny-apps
library(plotly)
library(worrms)
library(vegan)
library(forcats)
library(shinycssloaders)
